config/routes.rb
Rails.application.routes.draw do

  resources :lists 
  devise_for :users, controllers: { registrations: "registrations" }
  resources :genres
  resources :episodes
  resources :seasons
  resources :series do 
    member do 
      post 'track'
      delete 'untrack'
    end
    collection do 
      get 'autocomplete'
    end
  end
  
  
  

  root 'series#index'

end

app/models/season.rb
class Season < ActiveRecord::Base
	after_create :find_episodes
	validates :season_number, uniqueness: {scope: :series_id}
	default_scope { order('season_number DESC') }
	
	belongs_to :series
	has_many :episodes

	def find_episodes
		season_id = self.id
		series_id = self.series_id
		season_url = self.url
		page = ("http://www.imdb.com"+season_url)
		doc = Nokogiri::HTML(open(page))
		doc.css('div.list_item').each do |episode|
			title = episode.css('div.info a[itemprop = "name"]').text
			description = episode.css('div.item_description').text
			air_date = episode.css('div.airdate').text
			Episode.create(:title => title, :description => description, :air_date => air_date, :season_id => season_id, :series_id => series_id)
		end
	end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @series = Series.find(params[:series_id])
    @season = Season.new(season_params)
    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:season_number, :desription, :url, :series_id, :premiere)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :season_number %><br>
    <%= f.number_field :season_number %>
  </div>
  <div class="field">
    <%= f.label :desription %><br>
    <%= f.text_field :desription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seasons</h1>

<table>
  <thead>
    <tr>
      <th>Season number</th>
      <th>Desription</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.season_number %></td>
        <td><%= season.description %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<h1><%= @series.title %></h1>

<p>
  <strong>Season number:</strong>
  <%= @season.season_number %>
</p>

<% @season.episodes.each do |episode| %>
	<p><%= episode.title %></p>
	<p><%= episode.description %></p>
	<p><%= episode.air_date %></p>
<% end %>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>