config/routes.rb
Rails.application.routes.draw do

  resources :lists 
  devise_for :users, controllers: { registrations: "registrations" }
  resources :genres
  resources :episodes
  resources :seasons
  resources :series do 
    member do 
      post 'track'
      delete 'untrack'
    end
    collection do 
      get 'autocomplete'
    end
  end
  
  
  

  root 'series#index'

end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html

  def track
    @series = Series.find(params[:id])
    @series.users << current_user
    respond_to do |format|
        format.html { redirect_to series_url }
    end
    rescue => e 
      flash[:notice] = "You're already tracking that series!"
      redirect_to(:action => 'show')
  end

  def untrack
    @series = Series.find(params[:id])
    current_user.lists.find_by_series_id(@series.id).destroy if current_user
    respond_to do |format|
      format.html { redirect_to series_index_url}
    end
    rescue => e 
      flash[:notice] = "You aren't tracking that series!"
      redirect_to(:action => 'show')
  end

  # GET /series
  # GET /series.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development?
        @series = Series.where("title LIKE ?", "%#{search_term}%")
      else
        @series = Series.where("title ilike ?", "%#{search_term}%")
      end
    else
      @series = Series.all.paginate(:page => params[:page], :per_page => 50)
    end
  end

  def autocomplete
    @series = Series.order(:title).where("title LIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { 
        render json: @series.map(&:title).to_json
      }
  end
end

  # GET /series/1
  # GET /series/1.json
  def show
     @series = Series.find_by_id(params[:id])
     if current_user && user_signed_in? 
      @list = List.where(user_id: current_user.id, series_id: @series.id)
    else
    end
  end

  

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
    @series = Series.find_by_id(params[:id])
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)
    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, notice: 'Series already exits!' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    @series = Series.find_by_id(params[:id])
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :description, :network, :premiere, :cast, :creator, :genre_id, :poster, :url)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
  <%= form_for(@series) do |f| %>
    <% if @series.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

        <ul>
          <% @series.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
      <div class="form-group">
        <%= f.label :title, 'Series Title' %><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit  "Find Info", id: 'submit', data: { disable_with: "Finding Info" } %>
      </div>
  <% end %>

app/views/series/_series.html.erb
<div class="col-xs-6 col-sm-2 col-md-2 col-lg-2 seriesGrid">
    <div class="seriesTitle">
        <%= link_to image_tag(series.poster), series %>
       	<h3><%= link_to(series.title, series) %></h3>
        <p><strong>Next Episode:</strong>
            <% if series.next_episode === series.previous_episode %>
                TBA
            <% else %>
                <%= series.next_episode.air_date %> <%= series.next_episode.title %>
            <% end %>
        </p>
        <p><strong>Last Episode:</strong>
            <% if series.previous_episode %>
                <%= series.previous_episode.air_date %> <%= series.previous_episode.title %>
            <% else %>
                NA
            <% end %>
        </p>
    </div>
</div>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form' %>

app/views/series/index.html.erb
<div class="series">
	
	<div class="form-group" id="series-search">
    	<%= form_tag("/series", method: "get", class: "form-inline", id: "search-form") do %>
        	<%= text_field_tag :q, "", class: 'form-control search-query', id: "series-search-input", placeholder:'Search' %>
        <% end %>
    </div>
    <div id="new-series">
        <p>Don't see what you're looking for? <%= link_to 'Add a new series', new_series_path %></p>
    </div>
	<div class="row" id="seriesIndex">
    	<%= render @series %>
	</div>
	<br>
    <% if params[:q] %>
    <% else %>
        <div class="apple_pagination"> 
            <%= will_paginate @series %>
        </div>
    <% end %>
	   
    
</div>

app/views/series/new.html.erb
<div class="series">
	<h1>New Series</h1>

	<%= render 'form' %>

	
</div>

app/views/series/show.html.erb
<div class="seriesInfo">
	<div id="poster">
		<img src="<%= @series.poster %>">
	</div>
	<h1>
	  <%= @series.title %>
	</h1>
	<% if current_user && user_signed_in? %>
		<div id="addSeries">
			<% if @list.exists? %>
				<h3><%= link_to "Untrack", untrack_series_path(@series), :method => "delete" %></h3>
			<% else %>
				<h3><%= link_to "Track", track_series_path(@series), :method => "post" %></h3>
			<% end %>
		</div>
	<% end %>
	<div id="seriesDescription">
		<p><%= @series.description %></p>
	</div>
	<div id="extraInfo">
		<p><strong>Cast:</strong> <%= @series.cast %></p>
		<% if @series.creator === "" %>
		<% else %>
			<p><strong>Created by:</strong> <%= @series.creator %></p>
		<% end %>
		<p><strong>Next Episode:</strong>
			<% if @series.next_episode === @series.previous_episode %>
                TBA
            <% else %>
                <%= @series.next_episode.air_date %> <%= @series.next_episode.title %>
            <% end %>
			</p>
			<p><strong>Last Episode:</strong>
            <% if @series.previous_episode %>
                <%= @series.previous_episode.air_date %> <%= @series.previous_episode.title %>
            <% else %>
                NA
            <% end %>
        </p>
	</div>

	<div class="seasonList">
		<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
			<% @series.seasons.each do |season| %>
			
				<div class="panel">
				    <div class="panel-heading" role="tab" id="heading<%= season.season_number %>">
				      <h4 class="panel-title">
				        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= season.season_number %>" aria-expanded="false" aria-controls="collapse<%= season.season_number %>">
				          Season <%= season.season_number %>
				        </a>
				        <!--
				        <% if current_user && current_user.admin? %>
				        <%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %>
			  			<% end %> -->
				      </h4>
				    </div>
				    <div id="collapse<%= season.season_number %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= season.season_number %>">
				      <div class="panel-body">
				      	<% if season.episodes.exists? %>
					      	<% season.episodes.each do |episode| %>
								<h4><%= episode.title %></h4>
								<% if episode.description.include? "add a plot" %>
									<p>TBA</p>
								<% else %>
									<p><%= episode.description %></p>
								<% end %>
								<p><strong>Air Date:</strong>
									<% if episode.air_date %>
									 	<%= episode.air_date %>
									<% else %>
										TBA
									<% end %>
								</p>
							<% end %>
						<% else %>
							<h4>Season confirmed but no episode information exists yet.</h4>
						<% end %>
				      </div>
					</div>
			  	</div>
			<% end %>
			
		</div>
	</div>
</div>

<% if current_user && current_user.admin? %>
	<%= link_to 'Edit', edit_series_path(@series) %> |
	<%= link_to 'Back', series_index_path %> |
	<%= link_to 'Delete', @series, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>